"""add card url

Revision ID: 1665e2d7ea5e
Revises: b00094b25ce9
Create Date: 2020-03-22 19:12:47.801778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1665e2d7ea5e'
down_revision = 'b00094b25ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('url', sa.String(), nullable=True))
    op.create_index(op.f('ix_card_url'), 'card', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_url'), table_name='card')
    op.drop_column('card', 'url')
    # ### end Alembic commands ###
