"""add image src

Revision ID: 65a57c072291
Revises: 5b87cd933ee0
Create Date: 2020-03-22 20:43:01.998356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65a57c072291'
down_revision = '5b87cd933ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'img_url')
    # ### end Alembic commands ###
